---
title: "COVID-19 and GHG Emissions, What Can We Learn?"
author: "Justin Rhinehart @ jjrhine@uw.edu, Ryan Friesz @ ref7@uw.edu, Tom Jubin @ tomjubin@uw.edu, Liam Dale @ liamdale@uw.edu"
date: "2/18/2022"
output: html_document
---

<!-- 
[]INSERT P01
[]WRITE AUDIENCE PARAGRAPH
[]WRITE SUMMARY PARAGRAPH
[x]LINK CHARTS/TABLES 
-->

<!-- SOURCING FILES -->
```{r, echo = FALSE, warning=FALSE}
source("../source/c01_climate_model.R")
average_percentage_change <- average_percentage_change

source("../source/c02_Euro_avg.R")
# some_figs <- map_variable_here

source("../source/c03_co2_emissions_map.R")
# some_figs <- map_variable_here

```

<!-- VARIABLES!!!
average_percentage_change <- AVG. MODEL EMISSIONS VS REAL WORLD PERCENT DIFF. (14.28% decrease)
German_co2_2020 <- GERMANY CO2 2020
Brazil_c02_2020 <- BRAZIL CO2 2020
Venezuala_co2_2020 <- VENEZUALA CO2 2020
-->

# SUMMARY PARAGRAPH


# TABLE
```{r}
# source("../source/ghg_table.R")
```

# CHART 1
```{r, echo = FALSE, warning=FALSE}
source("../source/c01_climate_model.R")
ggplotly(line_graph)
```

# CHART 2
```{r, echo = FALSE, warning=FALSE}
source("../source/c02_euro_avg.R")
print(bar_graph)
```

# CHART 3
```{r, echo = FALSE, warning=FALSE}
source("../source/c03_co2_emissions_map.R")
ggplotly(co2_emissions_map)
```
